services:
  frontend:
    build: 
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}


  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy

    environment:
      - DB_STRING=${DB_STRING}
      - ALEMBIC_DB_URL=${ALEMBIC_DB_URL}
      - DEBUG=${DEBUG}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
      - APP_EMAIL_ADDRESS=${APP_EMAIL_ADDRESS}
      - EMAIL_TEMPLATES_PATH=${EMAIL_TEMPLATES_PATH}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
  db:
    image: postgres:17

    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbadmin -d ${PG_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
